inherit_gem:
  boost-styles:
    - rubocop_default.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/bundle
    - db/seeds.rb
    - spec/spec_helper.rb

Layout/LineLength:
  TargetRubyVersion: 2.6.5
  IgnoredPatterns:
    - 'it .* do$'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Enabled: true
  Max: 80
