inherit_gem:
  boost-styles:
    - rubocop_default.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/bundle
    - db/seeds.rb
    - spec/spec_helper.rb

Layout/LineLength:
  Max: 95
  IgnoredPatterns:
    - 'it .* do$'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

RSpec/NestedGroups:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
