inherit_gem:
  boost-styles:
    - rubocop_default.yml

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/bundle

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Enabled: true
  Max: 80
